---
resources:
  - name: ConcourseTestingExample(master)
    type: git
    source:
      uri: git@github.homedepot.com:zxs5629/ConcourseTestingExample-.git
      branch: master

jobs:
  - name: HelloWorld
    plan:
    - get: ConcourseTestingExample(master)
    - task: echo
      file: CI/helloWorld.yml
