---
resources:
  - name: ConcourseTestingExample(master)
    type: git
    source:
      uri: git@github.homedepot.com:zxs5629/ConcourseTestingExample-.git
      branch: master
      private_key: {{github-private-key}}

jobs:
- name: test
  plan:
  - get: ConcourseTestingExample(master)
    trigger: true
  - task: mvn-test
    file: ConcourseTestingExample(master)/CI/test.yml
    input_mapping:
      code-repo: ConcourseTestingExample(master)
- name: deploy
  plan:
  - get: ConcourseTestingExample(master)
    trigger: true
    passed: [test]
  - task: mvn-deploy
    file: ConcourseTestingExample(master)/CI/deploy.yml
    input_mapping:
      code-repo: ConcourseTestingExample(master)