---
resources:
  - name: ConcourseTestingExample(master)
    type: git
    source:
      uri: git@github.homedepot.com:zxs5629/ConcourseTestingExample-.git
      branch: master
      private_key: {{github-private-key}}

jobs:
  - name: HelloWorld
    plan:
    - get: ConcourseTestingExample(master)
      trigger: true
    - task: echo
      file: ConcourseTestingExample(master)/CI/helloWorld.yml
      input_mapping:
        code-repo: ConcourseTestingExample(master)